alter session set "_ORACLE_SCRIPT"=true;

CREATE USER CLAIMDB IDENTIFIED BY CLAIMDB;

CREATE TABLE CLAIMDB.ACCIDENT ( 
	ACCIDENT_ID          number(1)  NOT NULL,
	ACCIDENT_DATE        date  ,
	ACCIDENT_DESCRIPTION varchar2(255)  ,
	ACCIDENT_LOCATION    varchar2(255)  ,
	CONSTRAINT PK_ACCIDENT_ACCIDENT_KEY PRIMARY KEY ( ACCIDENT_ID ) 
 );

CREATE TABLE CLAIMDB.CLAIMANT ( 
	CLAIMANT_ID          number(1)  NOT NULL,
	CLAIMANT_NAME        varchar2(100)  ,
	CLAIMANT_ADDRESS     varchar2(100)  ,
	CLAIMANT_DATE_OF_BIRTH date  ,
	CONSTRAINT PK_CLAIMANT_CLAIMANT_ID PRIMARY KEY ( CLAIMANT_ID ) 
 );

CREATE TABLE CLAIMDB.EXPERT ( 
	EXPERT_ID            number(1)  NOT NULL,
	EXPERT_NAME          varchar2(100)  ,
	EXPERT_ADDRESS       varchar2(100)  ,
	EXPERT_EXPERTISE     varchar2(100)  ,
	CONSTRAINT PK_EXPERT_EXPERT_ID PRIMARY KEY ( EXPERT_ID ) 
 );

CREATE TABLE CLAIMDB.PAYMENT ( 
	PAYMENT_ID           number(1)  NOT NULL,
	PAYMENT_DATE         date  ,
	PAYMENT_AMOUNT       number(6,2)  ,
	PAYMENT_REASON       char(255)  ,
	PAYMENT_CHECK_NO     number(1)  ,
	CONSTRAINT PK_TBL_PAYMENT_ID PRIMARY KEY ( PAYMENT_ID ) 
 );

CREATE TABLE CLAIMDB.REPORT ( 
	REPORT_ID            number(1)  NOT NULL,
	REPORT_REQUEST_DATE  date  ,
	REPORT_SUBMIT_DATE   date  ,
	REPORT_CONTENT       char(255)  ,
	EXPERT_ID            number(1)  ,
	CONSTRAINT PK_REPORT_REPORT_ID PRIMARY KEY ( REPORT_ID ) 
 );

CREATE TABLE CLAIMDB.STAFF ( 
	STAFF_ID             number(1)  NOT NULL,
	STAFF_NAME           varchar2(100)  ,
	STAFF_ROLE           varchar2(255)  ,
	CONSTRAINT PK_STAFF_STAFF_ID PRIMARY KEY ( STAFF_ID ) 
 );

CREATE TABLE CLAIMDB.CLAIM ( 
	CLAIM_ID             number(1)  NOT NULL,
	CLAIM_STATE          varchar2(100)  ,
	CLAIM_NATURE         varchar2(100)  ,
	CLAIM_REPORT_DATE    date  ,
	STAFF_ID             number(1)  ,
	CLAIMANT_ID          number(1)  ,
	ACCIDENT_ID          number(1)  ,
	REPORT_ID            number(1)  ,
	PAYMENT_ID           number(1)  ,
	CONSTRAINT PK_MAIN_CLAIM_CLAIM_ID PRIMARY KEY ( CLAIM_ID ) ,
	CONSTRAINT UNQ_CLAIM_PAYMENT_ID UNIQUE ( PAYMENT_ID ) ,
	CONSTRAINT UNQ_CLAIM_REPORT_ID UNIQUE ( REPORT_ID ) ,
	CONSTRAINT UNQ_CLAIM_ACCIDENT_ID UNIQUE ( ACCIDENT_ID ) ,
	CONSTRAINT UNQ_CLAIM_CLAIMANT_ID UNIQUE ( CLAIMANT_ID ) 
 );

ALTER TABLE CLAIMDB.CLAIM ADD CONSTRAINT FK_CLAIM_STAFF FOREIGN KEY ( STAFF_ID ) REFERENCES CLAIMDB.STAFF( STAFF_ID );

ALTER TABLE CLAIMDB.CLAIM ADD CONSTRAINT FK_CLAIM_PAYMENT FOREIGN KEY ( PAYMENT_ID ) REFERENCES CLAIMDB.PAYMENT( PAYMENT_ID );

ALTER TABLE CLAIMDB.CLAIM ADD CONSTRAINT FK_CLAIM_REPORT FOREIGN KEY ( REPORT_ID ) REFERENCES CLAIMDB.REPORT( REPORT_ID );

ALTER TABLE CLAIMDB.CLAIM ADD CONSTRAINT FK_CLAIM_ACCIDENT FOREIGN KEY ( ACCIDENT_ID ) REFERENCES CLAIMDB.ACCIDENT( ACCIDENT_ID );

ALTER TABLE CLAIMDB.CLAIM ADD CONSTRAINT FK_CLAIM_CLAIMANT FOREIGN KEY ( CLAIMANT_ID ) REFERENCES CLAIMDB.CLAIMANT( CLAIMANT_ID );

ALTER TABLE CLAIMDB.REPORT ADD CONSTRAINT FK_REPORT_EXPERT FOREIGN KEY ( EXPERT_ID ) REFERENCES CLAIMDB.EXPERT( EXPERT_ID );

